details/urls.py
from django.conf.urls import url
from . import views

app_name = 'details'

urlpatterns = [   
    url(r'^$',views.stud_list, name="list"),
    url(r'^fee-record/$',views.fee_record,name="fee_record"),
    url(r'^(?P<usn>[\w]+)/$',views.stud_details, name="details"),
]

entry/urls.py
from django.conf.urls import url
from . import views

app_name = 'entry'

urlpatterns = [
    
    url(r'^create-stud-pd/$',views.stud_pd_entry,name="create_stud_pd"),
    url(r'^delete-stud-pd/(?P<usn>[\w]+)/$',views.delete_stud_pd,name="delete_stud_pd"),
    url(r'^fee/(?P<usn>[\w]+)/$',views.update_stud_fee, name="update_stud_fee"),
]

project/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    
    url(r'^accounts/',include('accounts.urls')),
    url(r'^entry/',include('entry.urls')),
    url(r'^details/',include('details.urls')),
    url(r'^$',views.home,name="index"),
]

urlpatterns += staticfiles_urlpatterns()

details/models.py
from django.db import models

# Create your models here.

details/views.py
from django.shortcuts import render
from entry.models import Stud_PD, Stud_Admn, Fee_Record, Stud_Fees
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required

@login_required(login_url="/accounts/login/")
def stud_list(request):
    class data:
        def __init__(self,name,usn,due,total):
            self.Sname=name
            self.USN=usn
            self.Due=due
            self.Total=total
    if request.method=='POST':
        text=request.POST['search']
        search = []
        if text:
            match = Stud_PD.objects.filter(Q(Sname__icontains=text) |
                                         Q(USN__icontains=text)    
                                        ) 
            if match!=None:
                for s in match:
                    try:
                        stud_ad = Stud_Admn.objects.get(Sid=s.Sid)
                    except Exception as e:
                        continue
                    finally:
                        stud_fee = Stud_Fees.objects.get(Adm_No_S=stud_ad.Adm_No)
                        search.append(data(s.Sname,s.USN,stud_fee.Due,stud_fee.Total))
                return render(request, 'details/stud_list.html',{'search':search,'text':text})       
        else:
            return HttpResponseRedirect('/details/')
    else:
        datalist = []
        stud_pds = Stud_PD.objects.all()
        for s in stud_pds:
            try:
                stud_ad = Stud_Admn.objects.get(Sid=s.Sid)
            except Exception as e:
                continue
            finally:
                stud_fee = Stud_Fees.objects.get(Adm_No_S=stud_ad.Adm_No)
                datalist.append(data(s.Sname,s.USN,stud_fee.Due,stud_fee.Total))
        return render(request, 'details/stud_list.html', {'datalist':datalist})

@login_required(login_url="/accounts/login/")
def stud_details(request,usn):
    stud_pd = Stud_PD.objects.get(USN=usn)
    stud_ad = Stud_Admn.objects.get(Sid=stud_pd.Sid)
    return render(request, 'details/stud_details.html', {'stud_pd':stud_pd, 'stud_ad':stud_ad})

@login_required(login_url="/accounts/login/")
def fee_record(request):   
    if request.method=='POST':
        text=request.POST['search']
        if text:
            match=Fee_Record.objects.filter(Q(Stud_Fee_ID__Adm_No_S__Adm_No__icontains=text) |
                                            Q(Added_by__username__icontains=text) |
                                            Q(Date_Paid__icontains=text)
                                            ) 
            if match!=None:
                return render(request, 'details/fee_record.html',{'search':match,'text':text})
        else:
            return HttpResponseRedirect('/details/fee-record/')
    else:
        fee_rcd=Fee_Record.objects.all()
        return render(request,'details/fee_record.html',{'fee_rcd':fee_rcd})

details/templates/details/fee_record.html
{%extends 'base_layout.html'%}

{% block content %}
<br/>
    <div class="container">
    <form class="form-inline" action="{% url 'details:fee_record'%}" method="post">
    {% csrf_token %}

        <h3><strong>Search Fee Record : </strong></h3>
        <div class="search-box">
            <input type="text" name="search" class="form-control" placeholder="Enter Date or User or Admission No">
        </div>
        <div class="search-button-align">
            <button type="submit" class="btn btn-primary">Search</button>
        </div>
    </form><br/>
</div>
<div class="container">
{%if search%}
    
    {%if search%}
    <div class='stud_pds'>
        <div class='stud_pds'>

            <h4 class="text-success">Search results for '{{text}}' :</h4>
    </div>
        <table class="table table-striped table-bordered table-hover table-condensed">
            <tr>
                <th>Student Admission No.</th>
                <th>Fee Paid</th>
                <th>Date & Time Paid</th>
                <th>Authorized By</th>
            </tr>
    	{%for s in search%}
            <tr>
                <td>{{s.Stud_Fee_ID}}</td>
                <td>{{s.Fee_Paid}}</td>
                <td>{{s.Date_Paid}}</td>
                <td>{{s.Added_by}}</td>
            </tr>
        {% endfor %}
        </table>
    </div>
    {%endif%}
</div>
{%else%}

    {%if fee_rcd%}
    <div class="container">

        <h3 class="stud-pd">Fee Record :</h3>
        <table class="table table-striped table-bordered table-hover table-condensed">
            <tr>
                <th>Student Admission No.</th>
                <th>Fee Paid</th>
                <th>Date & Time Paid</th>
                <th>Authorized By</th>
            </tr>
            {%for f in fee_rcd%}
            <tr>
                <td>{{f.Stud_Fee_ID}}</td>
                <td>{{f.Fee_Paid}}</td>
                <td>{{f.Date_Paid}}</td>
                <td>{{f.Added_by}}</td>
            </tr>
            {%endfor%}
        </table>
    </div>
    {%else%}

    <div class="container">
    <div class="alert alert-warning" role="alert">
    <h3>Results Not Found</h3>
</div>
</div>
    {%endif%}
{%endif%}
{% endblock %}

details/templates/details/stud_details.html
{%extends 'base_layout.html'%}

{% block content %}
    
    <br/>
    <div class="container">
        <table class="table table-striped table-bordered table-hover table-condensed" >
	        <tr><td><h1>Name </h1></td> <td><h1>{{stud_pd.Sname}}</h1></td></tr>
            <tr><td><h3>USN </h3></td> <td><h3>{{stud_pd.USN}}</h3></tr>
            <tr><td><p>Gender</p> </td> <td><p> {{stud_pd.Gender}}</p></tr>
            <tr><td><p>Date Of Birth</p> </td> <td><p>{{stud_pd.DOB}}</p></tr>
            <tr><td><p>Place Of Birth</p></td> <td><p>{{stud_pd.POB}}</p></tr>
            <tr><td><p>Phone Number </p></td> <td> <p>{{stud_pd.S_Pno}}</p></tr>
            <tr><td><p>Address </p></td> <td><p> {{stud_pd.S_Add}}</p></tr>
            <tr><td><p>Batch  </p></td> <td><p>{{stud_pd.Batch}}</p></tr>
            <tr><td><strong>Admission Number</strong>  </td> <td><strong>{{stud_ad.Adm_No}}</strong></tr>
            <tr><td><p>Course  </p></td> <td><p>{{stud_ad.Course}}</p></tr>
            <tr><td><p>Semester </p></td> <td><p>{{stud_ad.Sem}}</p></tr>
            <tr><td><p>Branch </p></td> <td><p>{{stud_ad.Branch}}</p></tr>
            <tr><td><p>Admission Type </p></td> <td><p> {{stud_ad.Adm_Type}}</p></tr>
            <tr><td><p>Quota </p></td> <td><p>{{stud_ad.Quota}}</p></tr>
        </table>         
    </div>
    <div class="container">
        <div class="text-center">
        <button class="btn btn-success"><h5 ><a style="color:black" href="{% url 'entry:update_stud_fee' usn=stud_pd.USN %}">Update Student Fee</a></h5></button>
        <br/>
        </div>
    </div>
    <div class="container">
        <div class="text-center">
        <br/>
        <button class="btn btn-danger"><h5 ><a style="color:black" href="{% url 'entry:delete_stud_pd' usn=stud_pd.USN %}">Delete Student PD</a></h5></button>
    </div>
    </div>
{% endblock %}

details/templates/details/stud_list.html
{%extends 'base_layout.html'%}
{% load static from staticfiles %}

{% block content %}

<br/>
    <div class="container">
        <div class="text-center">
        <h2 id="stotal"></h2>
    </div>
    </div>
    <div class="container">
    <div class="text-center">
        <form class="form-inline" action="{% url 'details:list'%}" method="post">
        {% csrf_token %}

        <h3><strong>Search Student : </strong></h3>
        <div class="form-group">
        <div class="text-center">

            <input type="text" name="search" class="form-control" placeholder="Enter Student's Name or USN">
        </div>
        </div>
        <div class="search-button-align">
            <button type="submit" class="btn btn-primary">Search</button>
        </div>
        </form><br/>
        <form class="form-inline">
        <label for="id_sort"><h3><strong>Sort by :</strong></h3></label>
        <select class="form-control" id="id_sort">
            <option value="none" id="n" >None</option>
            <option value="noDue" id="nd" >No Due</option>
            <option value="paid75" id="pd" >Paid 75%</option>
            <option value="plt75" id="plt" >Paid less than 75%</option>
        </select>
        </form>
        <br/>
    </div>
    </div>
<div class="container">
{%if search%}   
    <div class='stud_pds'>
            <h4 class="text-success">Search results for '{{text}}' :</h4>
    </div>
    <div class="container">
        <table class="table table-striped table-bordered table-hover table-condensed" >
            
            <tr>
                <th>Name</th>
                <th>USN</th>
                <th>Total Fees</th>
                <th>Due : Click To Pay</th>
            </tr>
    	{%for s in search%}
            <tr id="sdetails">
                <td><a href="{% url 'details:details' usn=s.USN %}">{{s.Sname}}</a></td>
                <td><a href="{% url 'details:details' usn=s.USN %}">{{s.USN}}</a></td>
                <td>{{s.Total}}</td> 
                <td><a href="{% url 'entry:update_stud_fee' usn=s.USN %}">{{s.Due}}</a></td>
            </tr>
        {% endfor %}
        </table>
    </div>
</div>
{%else%}
	{%if datalist %}
    <div class='container'>

        <h3 class="stud-pd">Students List :</h3>
    <table class="table table-striped table-bordered table-hover table-condensed" id="table">
        <tr>
                <th>Name</th>
                <th>USN</th> 
                <th>Total Fees</th>
                <th>Due : Click To Pay</th>
        </tr>
    	{%for s in datalist%}
		<div class='stud'>
            <tr id="sdetails">
                <td><a href="{% url 'details:details' usn=s.USN %}" >{{s.Sname}}</a></td>
                <td><a href="{% url 'details:details' usn=s.USN %}" >{{s.USN}}</a></td>
                <td>{{s.Total}}</td>              
                <td><a href="{% url 'entry:update_stud_fee' usn=s.USN %}">{{s.Due}}</a></td>
            </tr>
        {% endfor %}
        </div>

    <table>
    </div>
    {% else %}
    <div class="container">
    <div class="alert alert-warning" role="alert">
        <h3>Results Not Found</h3>
    </div></div>
    {% endif %}
{%endif%}
<script src="{% static 'stud_list.js' %}"></script>  
{% endblock %}