accounts/urls.py
from django.conf.urls import url
from . import views
from .forms import LoginForm

app_name='accounts'

urlpatterns = [   
    url(r'^login/$',views.login_view,name="login"),
    url(r'^logout/$',views.logout_view,name="logout"),
]

details/urls.py
from django.conf.urls import url
from . import views

app_name = 'details'

urlpatterns = [   
    url(r'^$',views.stud_list, name="list"),
    url(r'^fee-record/$',views.fee_record,name="fee_record"),
    url(r'^(?P<usn>[\w]+)/$',views.stud_details, name="details"),
]

entry/urls.py
from django.conf.urls import url
from . import views

app_name = 'entry'

urlpatterns = [
    
    url(r'^create-stud-pd/$',views.stud_pd_entry,name="create_stud_pd"),
    url(r'^delete-stud-pd/(?P<usn>[\w]+)/$',views.delete_stud_pd,name="delete_stud_pd"),
    url(r'^fee/(?P<usn>[\w]+)/$',views.update_stud_fee, name="update_stud_fee"),
]

project/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    
    url(r'^accounts/',include('accounts.urls')),
    url(r'^entry/',include('entry.urls')),
    url(r'^details/',include('details.urls')),
    url(r'^$',views.home,name="index"),
]

urlpatterns += staticfiles_urlpatterns()

templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<title>Fee Management</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
	><nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{% url 'index' %}"><h2>Home</h2></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    {% if user.is_authenticated %}
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link">Logged-In as "{{user.username}}" <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'entry:create_stud_pd' %}">Add Student Data</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'accounts:logout' %}" method="post">
    {% csrf_token %}
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Logout</button>
    </form>
    {% else %}
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <button class="btn btn-secondary my-2 my-sm-0">
                <a class="nav-link" href="{% url 'accounts:login' %}"><strong>Log-In</strong></a>
            </button>
        </li>
    </ul>
    {% endif %}
  </div>
</nav>
    <div style="margin-top:50px;"></div>
{% block content %}
{% endblock %}
    <div style="margin-top:200px;"></div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{%extends 'base_layout.html'%}

{% block content %}

<div class="jumbotron text-center">
    <div class="container">
        <h1><strong>Student Fees Management System</strong></h1>
    </div>
    <br>
    <br>
    <div class="row">
      	<div class="col-md-6">
      	<h5>To get the list of the Students, Click below:</h5>
      	<button class="btn btn-primary"><a href="{% url 'details:list' %}" class="btn btn-success">Student List</a></button>
      	<br>
    	<br>
		</div>
      	<div class="col-md-6">
      		<h5>To get the Fees Record, Click below:</h5>
      		<button class="btn btn-primary"><a href="{% url 'details:fee_record' %}" class="btn btn-info">Fee Record</a></button>
      	<br>
    	<br>
		</div>
  	</div>
</div>
	
{% endblock  %}